services:
  iserve_map_humble:
    image: iserverobotics/iserve_map:humble
    container_name: iserve_map_humble
    restart: unless-stopped
    profiles: ["humble"]

    shm_size: '2gb'
    network_mode: host

    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-42}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
      - TARGET_CONTAINER=${TARGET_CONTAINER:-nav_autonomy}
      - OUTPUT_DIR=/iserve_ws/logs/monitor
      - INTERVAL=${MONITOR_INTERVAL:-1.0}
      - LOG_OUTPUT_DIR=/iserve_ws/logs/analyzer
      - SUMMARY_INTERVAL=${SUMMARY_INTERVAL:-60}

    volumes:
      - ./maps:/iserve_ws/maps:rw
      # Docker socket for nav_autonomy monitoring and log analysis
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Persist CPU/memory monitor logs
      - ./logs/monitor:/iserve_ws/logs/monitor:rw
      # Persist log analyzer output
      - ./logs/analyzer:/iserve_ws/logs/analyzer:rw

    command:
      - bash
      - -c
      - |
        echo "=== iServe Map (Humble) ==="
        echo "ROS_DOMAIN_ID: $ROS_DOMAIN_ID"
        echo "Auto-save: ON | Publish: OFF"
        bash /iserve_ws/config/monitor.sh ${MONITOR_INTERVAL:-1} &
        ros2 launch iserve_map iserve_map.launch.py \
          params_file:=/iserve_ws/config/iserve_map_deploy.yaml &
        MAP_PID=$!
        sleep 2
        echo "Starting Foxglove Bridge on port 8766..."
        ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8766 &
        FG_PID=$!
        echo "Starting nav_autonomy monitor (target: $TARGET_CONTAINER)..."
        python3 /iserve_ws/scripts/nav_monitor.py &
        echo "Starting nav_autonomy log analyzer (target: $TARGET_CONTAINER)..."
        python3 /iserve_ws/scripts/log_analyzer.py &
        wait $MAP_PID $FG_PID

  iserve_map_jazzy:
    image: iserverobotics/iserve_map:jazzy
    container_name: iserve_map_jazzy
    restart: unless-stopped
    profiles: ["jazzy"]

    shm_size: '2gb'
    network_mode: host

    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-42}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTDDS_BUILTIN_TRANSPORTS=UDPv4
      - TARGET_CONTAINER=${TARGET_CONTAINER:-nav_autonomy}
      - OUTPUT_DIR=/iserve_ws/logs/monitor
      - INTERVAL=${MONITOR_INTERVAL:-1.0}
      - LOG_OUTPUT_DIR=/iserve_ws/logs/analyzer
      - SUMMARY_INTERVAL=${SUMMARY_INTERVAL:-60}

    volumes:
      - ./maps:/iserve_ws/maps:rw
      # Docker socket for nav_autonomy monitoring and log analysis
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Persist CPU/memory monitor logs
      - ./logs/monitor:/iserve_ws/logs/monitor:rw
      # Persist log analyzer output
      - ./logs/analyzer:/iserve_ws/logs/analyzer:rw

    command:
      - bash
      - -c
      - |
        echo "=== iServe Map (Jazzy) ==="
        echo "ROS_DOMAIN_ID: $ROS_DOMAIN_ID"
        echo "Auto-save: ON | Publish: OFF"
        bash /iserve_ws/config/monitor.sh ${MONITOR_INTERVAL:-1} &
        ros2 launch iserve_map iserve_map.launch.py \
          params_file:=/iserve_ws/config/iserve_map_deploy.yaml &
        MAP_PID=$!
        sleep 2
        echo "Starting Foxglove Bridge on port 8766..."
        ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8766 &
        FG_PID=$!
        echo "Starting nav_autonomy monitor (target: $TARGET_CONTAINER)..."
        python3 /iserve_ws/scripts/nav_monitor.py &
        echo "Starting nav_autonomy log analyzer (target: $TARGET_CONTAINER)..."
        python3 /iserve_ws/scripts/log_analyzer.py &
        wait $MAP_PID $FG_PID
